### ISSUE TITLE
Need SVG version of the Accelerate Networks logo

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/linphone-android#12]
This is actually for linphone-iphone, but we don't have that repo on github yet...
I need the SVG of the Accelerate networks logo because I need to create 30 different resolutions for the iphone app

**Comment by danry25** [comment]
[Take a look at the assets we have here](https://github.com/AccelerateNetworks/acceleratenetworks.com/tree/master/public), if you can't find a pre-rendered one of the right size then look in assets/img/logos for the original PNG ([like this one](https://github.com/AccelerateNetworks/acceleratenetworks.com/blob/master/public/assets/img/logos/accelerate-a%402x.png)).

**Comment by piajesse** [comment]
hmm, I would like to grab it from the original artwork, so that its less blury/broken up.
but I could make do, I will need the following resolutions...
- 40x40
- 60x60
- 58x58
- 87x87
- 80x80
- 120x120
- 180x180
- 20x20
- 29x29
- 76x76
- 152x152
- 167x167
- 1024x1024

Should I just grab recreate all the missing ones from that 204x200 image you linked?
or should I grab it from this higher res version
https://github.com/AccelerateNetworks/acceleratenetworks.com/blob/master/public/mstile-310x310.png

**Comment by danry25** [comment]
@piajesse I dug up the original SVGs that @lukevers sent my way, see your email. I did ask @uncheckederror to add these to the NumberSearch repo since that replaced our website a few years ago...

**Comment by piajesse** [comment]
Thanks!
