### ISSUE TITLE
Update default configuration to enable push notifications by default

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/linphone-android#6]
Enable push notifications by default in settings.

**Comment by danry25** [comment]
@piajesse Would you mind updating the status of this issue? IIRC doze mode and registration type (UDP, TCP & TLS) all play into this...

**Comment by piajesse** [comment]
Currently the most recent version of linphone for android which worked for testing the new lua version of the freeswitch-push project. By default linphone doesn't even send push notifactions details. You have to enable the setting for it to receive push notifactions, and from the looks of it doze mode is still pretty janky with linphone e.g.
- no way to manually set linphone to close, it does so randomly
- doesn't always ring the phone during a call
More testing is needed to figure out the exact causes and possible solutions.

**Comment by danry25** [comment]
@piajesse To recap recent progress, with Flexisip push notifications now work properly.
