### ISSUE TITLE
Setup Gitlab CI

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/linphone-android#7]

**Comment by thefinn93** [comment]
doesn't automatically sync, but the basic CI work to build the APK is there: https://git.callpipe.com/linphone/linphone-android

**Comment by thefinn93** [comment]
this should work fully now. There is a GitHub Actions job that just calls the GitLab API to start a GitLab job, which syncs the repo and triggers the real job. It seems to mostly work, so im gonna close this.
