### ISSUE TITLE
unable to post to google play store

### ISSUE THREAD

**Issue by piajesse** [AccelerateNetworks/linphone-android#8]
Unable to post the apk because of this error
![Screenshot_20210303_152716](https://user-images.githubusercontent.com/44306072/109886691-58cef080-7c35-11eb-8f6b-ddc33e1e89e3.png)

**Comment by piajesse** [comment]
Google has the following content for the privacy policy


Add a privacy policy to your store listing to help provide transparency about how you treat sensitive user and device data. [Learn more
](https://support.google.com/googleplay/android-developer/answer/9859152?hl=en&visit_id=637504095840987901-1537437611&rd=2#privacy)
You must add a privacy policy if your target audience includes children under 13. Check the [User Data policy](https://play.google.com/about/privacy-and-security.html) to avoid common violations.

**Comment by uncheckederror** [comment]
Here's the privacy policy: https://acceleratenetworks.com/privacy

**Comment by piajesse** [comment]
we have advertisers? lol
where did you get that template from? @uncheckederror

**Comment by uncheckederror** [comment]
> we have advertisers? lol
> where did you get that template from? @uncheckederror

@danry25 provided the template here https://github.com/AccelerateNetworks/NumberSearch/issues/162#issuecomment-790176327

**Comment by piajesse** [comment]
alright, its posted as a beta, now I have to figure out how to join said beta, lol, thanks Tom for the update!
